### ISSUE TITLE
Choosing a license for logo and other artistic assets

### ISSUE THREAD

**Issue by vmagnin** [fortran-lang/assets#3]
Following that [Discourse discussion](https://fortran-lang.discourse.group/t/modern-fortran-logo/2075/18), it seems necessary to reflect upon the license used for "artistic" assets, like the Fortran Logo.

At the moment, the whole content of Fortran-lang.org is under MIT license:
https://github.com/fortran-lang/fortran-lang.org/blob/master/LICENSE
which is focused on software and documentation.

A license such as [Creative Commons](https://en.wikipedia.org/wiki/Creative_Commons_license) would be more appropriate for artistic assets. For example, in [Wikimedia](https://commons.wikimedia.org/wiki/Commons:FAQ#What_licenses_do_the_files_I_want_to_upload_have_to_use?) files are often under a CC license: CC-0 (~public domain), CC-BY or CC-BY-SA.

**Comment by awvwgk** [comment]
Many projects also have a dedicated page to explain the licensing and usage terms of a logo. See [here](https://www.python.org/community/logos/) for the Python logo.

**Comment by vmagnin** [comment]
> See [here](https://www.python.org/community/logos/) for the Python logo.

So Python and its logo are trademarks from the Python Software Fondation:
https://www.python.org/psf/trademarks/

**Comment by vmagnin** [comment]
The Rust logo is CC-BY licensed by Mozilla:
https://www.rust-lang.org/policies/media-guide

The Julia logos are CC-BY-NC-SA 4.0:
https://github.com/JuliaLang/julia-logo-graphics

**Comment by aslozada** [comment]
> 

GNU License Logos: https://www.gnu.org/graphics/license-logos.en.html

Official logos:  GFDL
Alternative Logos: CC BY 3.0

**Comment by awvwgk** [comment]
While not official yet, I've have been using the “fpm color palette” for several Fortran related projects now.

![image](https://user-images.githubusercontent.com/28669218/146758459-cebe3f3a-80c5-4e9c-b775-ac0f3c80ef05.png)

So far it appears at:
- [French Wikipedia](https://fr.wikipedia.org/wiki/Fortran#Gestionnaire_de_paquets_et_syst%C3%A8mes_de_construction)
- [FortranCon/PackagingCon presentation of fpm](https://github.com/fortran-lang/talks)
- [fpm docs](https://fpm.fortran-lang.org)
- [TOML-Fortran logo](https://github.com/toml-f/toml-f/blob/main/assets/toml-f.png)

**Comment by gnikit** [comment]
IMO I think a decent license for artwork that we expect to be modified e.g. the F logo, should be licensed under CC-BY-NC-SA , while artwork that is meant to be in final products like fpm, fortls, stdlib, etc. should use something like  CC-BY-NC-SA or the more restrictive (CC BY-NC-ND 4.0).

In general, I think that we should limit the potential usage of the artwork for commercial purposes other than "Fortran-lang & friends" and doing this early on, while the organisation is relatively small helps keep things simple.

**Comment by awvwgk** [comment]
For artwork other than the logos, I personally prefer to release to the public domain which makes adoption by others in the community easier. For example the artwork from my FortranCon talk on fpm is available [here](https://github.com/awvwgk/fpm-artwork), one of the figures ended up on Wikipedia now.

**Comment by gnikit** [comment]
In general I don't really mind, as long as there is a general consensus about the license of the artwork in fortran-lang. It is just my personal preference that tends towards restrictive licenses for commercial usage, but whichever license we pick I will be happy.

I do however think that we might have to register a couple of logos as trademarks and restrict their usage, see [NumFOCUS](https://numfocus.org/trademark-guidelines#:~:text=registered%20or%20not.-,The%20trademarks%20for%20which%20we%20are%20not%20allowing%20any%20use,-The%20following%20trademarks) for example

**Comment by certik** [comment]
I suggest to stick with the current public domain / MIT license for logos to allow their wide adoption. We do not own Fortran, so I think restricting the logo usage is not right. Of course we do not want somebody using this logo for their product, but I think as we are getting more successful and well-known, this is less and less of an issue. The SymPy logo as an example is BSD licensed as well (https://github.com/sympy/svn_materials/tree/4c79cfc68a85a947c5d730ec57540b6dff322f2d/logo) and we never had any problems. If anybody used it in ways that we think are not right, we can simply point out and ask them to stop, and it's not a good look to steal a logo from an open source project.

We want people to use the Fortran logo anytime they mention Fortran, so I think it is in the best interests of everyone to keep it as open as we can. 

We can write up guidelines how we wish people to use the logo, but on legal terms I would keep it as open as we can. Just like with our open source code.

**Comment by gnikit** [comment]
Do you want to move this issue to https://github.com/fortran-lang/assets?

**Comment by gnikit** [comment]
Given that the logo, all the fpm artwork and all/any vscode assets are licensed under MIT, should we set the default license as MIT unless stated otherwise?
